apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-yqrr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-yqrr
    app.kubernetes.io/part-of: integ-app-lewu
  name: hacbs-test-project-yqrr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-yqrr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-yqrr
    spec:
      containers:
      - image: quay.io/rycole-appstudio/integration1-wvzm-tenant/integ-app-lewu/hacbs-test-project-yqrr@sha256:bf3ecdd0e34a1650f8c7fe6ed0645d46cb99f0e0d82799d497b660dc230e6881
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
